### ISSUE TITLE
Mime Type with accpet

### ISSUE THREAD

**Issue by notorioushanz** [themeteorchef/jquery-validation#10]
Hello,

How do i call plugin method such as accept?
I would like to validate file type before uploading it.

Thank You.

**Comment by themeteorchef** [comment]
Hi, take a peek at this: http://jqueryvalidation.org/accept-method/. You should be able to specify an `accept` property on the rule set for your input field, passing a MIME type to validate against.

**Comment by notorioushanz** [comment]
Thank you for the answer. I tried this but i have "TypeError: $.validator.methods[method] is undefined" in console.
My code is like that 
`Template.s3_upload.onRendered(function(){
  $(".s3upload").validate({
    rules: {
            filetitle: {
                required: true,
                minlength: 6
            },
            fileinput: {
              required: true,
              accept: "video/*"
            }
        }
  });
})`

**Comment by notorioushanz** [comment]
I find the anwser so i put it here.
I had to include `additional-methods.min.js` in the client folder
