### ISSUE TITLE
Angular 2.validate is not a function

### ISSUE THREAD

**Issue by savchukm** [themeteorchef/jquery-validation#18]
Hi!
I'm using angular 2 with jquery-validation, but have some troubles with it. Using documentation,  jquery-validation was installed: npm i jquery-validation --save
In my component:

```
ngOnInit() {
        (<any>$(".add-suggestion-form")).validate({
            rules: {
                description: {
                    required: true,
                    minlength: 5
                }
            },
            //For custom messages
            messages: {
                description:{
                    required: "Enter a username",
                    minlength: "Enter at least 5 characters"
                }
            },
            errorElement : "div",
            errorPlacement: function(error, element) {
                var placement = (<any>$(element)).data("error");
                if (placement) {
                    (<any>$(placement)).append(error)
                } else {
                    error.insertAfter(element);
                }
            }
        });
    }

```

In my component's template:
```
<form class="add-suggestion-form">
        <div class="add-suggestion-form__header">
            <div class="add-suggestion-form__header-text-info">
                <main-info-input></main-info-input>
             </div>
        </div>
        <div class="input-field">
            <textarea id="description" class="materialize-textarea" data-length="2500"></textarea>
            <label for="description">Description</label>
        </div>
    </form>
```
Following error was occured:

> EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: $(...).validate is not a function
> Error: Error in :0:0 caused by: $(...).validate is not a function
>     at ViewWrappedError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:116891:33)
>     at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:33504:16)
>     at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:33569:16)
>     at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:65721:16)
>     at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:90015:23)
>     at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:89988:18)
>     at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:66648:20)
>     at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:72156:42)
>     at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:28293:16)
>     at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:28260:26)
>     at http://localhost:4200/vendor.bundle.js:28196:58
>     at Array.forEach (native)
>     at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:28196:29)
>     at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:28240:22)
>     at http://localhost:4200/vendor.bundle.js:28196:58

**Comment by themeteorchef** [comment]
Hi. This should be asked on [the official jquery-validation repo](https://github.com/jquery-validation/jquery-validation). This package was for Meteor users but has been deprecated.
