### ISSUE TITLE
Is this package missing the 'pattern' method?

### ISSUE THREAD

**Issue by nathanhornby** [themeteorchef/jquery-validation#2]
I'm trying to use the [additional pattern method](https://github.com/jzaefferer/jquery-validation/blob/f59bb1389fb24c50c265b506235af7c900ee9597/src/additional/pattern.js) in `$.validator.setDefaults()`:

`$.validator.setDefaults({
  rules: {
    uri: {
      minlength: 3,
      pattern: /^[a-zA-Z_0-9-]+$/
    }
  }
});`

But on validate the console is giving me:

> Uncaught TypeError: Cannot read property 'call' of undefined

On line 601 of call.js:

`result = $.validator.methods[ method ].call( this, val, element, rule.parameters );`

**Edit:** It seems you need to explicitly include `additional-methods.js` to be able use this method - is there a recommended way to do this?

**Comment by themeteorchef** [comment]
It looks like an edit will need to be made to the package.js to make sure that file is loaded in. I can take a peek this week or feel free to do a PR for what you need and I'll merge :)

**Comment by nathanhornby** [comment]
If I get a chance to poke around I will (I'm not hugely familiar with the plugin or meteor packages though...), otherwise I'll keep my eyes peeled :) cheers!
