### ISSUE TITLE
onRendered not supported

### ISSUE THREAD

**Issue by jeblister** [themeteorchef/jquery-validation#5]
Hi,

I use the latest meteor release 1.1.0.3.

As you know after Meteor 1.0.4 rendered got deprecated and replaced by onRendered.

After using jguery-validation in my project i have a "wrong" behavior when using onRendered.

If use rendred method i don't have a issue.

**Comment by themeteorchef** [comment]
Can you describe the wrong behavior for me? This package is being used in [Base](https://github.com/themeteorchef/base) which relies on the `onRendered` syntax and hasn't had any issues to date. 

If you're getting an error message or anything more descriptive, please share so I can help to fix :)

**Comment by jeblister** [comment]
When i click to create an acount nothing happen and without a error message !
see this gif :
![](http://i.imgur.com/GpF7pwj.gifv)

**Comment by themeteorchef** [comment]
Can you post your GIF again? Getting a not found message from GitHub.

**Comment by jeblister** [comment]
http://i.imgur.com/GpF7pwj.gifv

**Comment by themeteorchef** [comment]
This looks like an issue with the source for that recipe. I'm going to close this here and move this over there.
